# -*- coding: utf-8 -*-
"""train.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ThkLKmi6ckk7s1J38xReuDcTa_OwQlpN
"""

results = model.train(
    data=data_yaml_path,
    epochs=30,  # Increase to 30
    imgsz=416,
    batch=batch_size,
    name='plastic_detection',
    project='/kaggle/working/plastic_detection',
    device=device,
    patience=10,
    save=True,
    save_period=2,
    exist_ok=True
)